from PIL import ImageFont

DIVIDER_SPACING = 76


class Colors:
    TRANSPARENT = (255, 255, 255, 0)
    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    GREY = (137, 140, 141)
    SHIP_NAME = WHITE
    POINT_VALUE = WHITE
    SHIP_TYPE_AND_YEAR = (134, 135, 137)
    STATS = WHITE
    ATTACK_VALUE_BACKGROUND = (0, 255, 0, 80) # transparent green


class Fonts:
    SHIP_NAME = ImageFont.truetype("assets/Komet - Flicker - B52-Regular.ttf", 75)
    POINT_VALUE = ImageFont.truetype("assets/Komet - Flicker - B52-Regular.ttf", 94)
    SHIP_TYPE_AND_YEAR = ImageFont.truetype("assets/Komet - Flicker - B52-Regular.ttf", 30)
    SHIP_SPEED = ImageFont.truetype("assets/Komet - Flicker - B52-Regular.ttf", 35)
    ATTACK_ARMOR_STATS_HEADINGS = ImageFont.truetype("assets/Komet - Flicker - B52-Regular.ttf", 30)
    ATTACK_ARMOR_STATS = ImageFont.truetype("assets/Komet - Flicker - B52-Regular.ttf", 70)


class Resizing:
    NATION_EMBLEM = (60, 60)


class Coordinates:
    NATION_EMBLEM = (45, 165)
    SHIP_NAME = (78, 91)
    SINGLE_DIGIT_POINT_VALUE = (625, 84)
    DOUBLE_DIGIT_POINT_VALUE = (597, 84)
    SHIP_TYPE = (128, 165)
    SHIP_YEAR = (510, 165)
    SHIP_SPEED = (130, 206)

    ATTACK_HEADING = (72, 257)
    ATTACK_RANGE_HEADING_0 = (240, ATTACK_HEADING[1])
    ATTACK_RANGE_HEADING_1 = (ATTACK_RANGE_HEADING_0[0] + 77, ATTACK_HEADING[1])
    ATTACK_RANGE_HEADING_2 = (ATTACK_RANGE_HEADING_1[0] + 74, ATTACK_HEADING[1])
    ATTACK_RANGE_HEADING_3 = (ATTACK_RANGE_HEADING_2[0] + 74, ATTACK_HEADING[1])

    ATTACK_HEADING_DIVIDER = [(210, 254), (210, 292)]
    ATTACK_HEADING_DIVIDER_1 = [
        (ATTACK_HEADING_DIVIDER[0][0] + DIVIDER_SPACING, ATTACK_HEADING_DIVIDER[0][1]),
        (ATTACK_HEADING_DIVIDER[1][0] + DIVIDER_SPACING, ATTACK_HEADING_DIVIDER[1][1])
    ]
    ATTACK_HEADING_DIVIDER_2 = [
        (ATTACK_HEADING_DIVIDER_1[0][0] + DIVIDER_SPACING, ATTACK_HEADING_DIVIDER[0][1]),
        (ATTACK_HEADING_DIVIDER_1[1][0] + DIVIDER_SPACING, ATTACK_HEADING_DIVIDER[1][1])
    ]
    ATTACK_HEADING_DIVIDER_3 = [
        (ATTACK_HEADING_DIVIDER_2[0][0] + DIVIDER_SPACING, ATTACK_HEADING_DIVIDER[0][1]),
        (ATTACK_HEADING_DIVIDER_2[1][0] + DIVIDER_SPACING, ATTACK_HEADING_DIVIDER[1][1])
    ]


class Values:
    ATTACK_HEADER_Y_END = 296

    ATTACK_RECTANGLE_START_Y = 295
    ATTACK_RECTANGLE_START_X = 210
    ATTACK_RECTANGLE_END_X = 513
    ATTACK_RECTANGLE_WIDTH = 55

    ATTACK_ICON_START_X = 56

    ATTACK_VERTICAL_DIVIDER_1 = 286
    ATTACK_VERTICAL_DIVIDER_2 = ATTACK_VERTICAL_DIVIDER_1 + DIVIDER_SPACING
    ATTACK_VERTICAL_DIVIDER_3 = ATTACK_VERTICAL_DIVIDER_2 + DIVIDER_SPACING
