name: Build Decks
on:
  push:
    branches:
      - master
jobs:
  build-decks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10 and Install Dependencies
        uses: ./.github/workflows/setup-python.yml
        with:
          python-version: "3.10"